# fly.toml app configuration file generated for wallet-linker on 2024-08-13T02:37:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wallet-linker"
primary_region = "ams"

[build]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
